"""
harness/utils/exporter.py — 從 completed_code 導出實際檔案到專案目錄。

執行完成後，將 HarnessState 中的 completed_code 寫入指定目錄，
讓生成的代碼變成可執行的專案。
"""
import os
from typing import Dict


def export_code_to_directory(
    completed_code: Dict[str, str],
    output_dir: str = "./output",
    overwrite: bool = False
) -> Dict[str, str]:
    """
    將 completed_code 導出到指定目錄。

    Args:
        completed_code: {filename: code_str} 字典
        output_dir: 輸出目錄路徑，預設 "./output"
        overwrite: 是否覆蓋已存在的檔案

    Returns:
        {filename: full_path} 字典，記錄每個檔案的完整路徑
    """
    if not completed_code:
        return {}

    # 創建輸出目錄
    os.makedirs(output_dir, exist_ok=True)

    exported_files = {}

    for filename, code in completed_code.items():
        # 建立完整路徑
        file_path = os.path.join(output_dir, filename)

        # 檢查檔案是否已存在
        if os.path.exists(file_path) and not overwrite:
            print(f"⚠️  Skip: {filename} (already exists)")
            continue

        # 寫入檔案
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
            exported_files[filename] = file_path
            print(f"✅ Exported: {filename}")
        except Exception as e:
            print(f"❌ Failed to export {filename}: {e}")

    return exported_files


def export_tests_to_directory(
    task_results: list,
    output_dir: str = "./output/tests",
    overwrite: bool = False
) -> Dict[str, str]:
    """
    將所有測試代碼導出到測試目錄。

    Args:
        task_results: list of TaskResult dicts
        output_dir: 測試輸出目錄
        overwrite: 是否覆蓋已存在的檔案

    Returns:
        {test_filename: full_path} 字典
    """
    if not task_results:
        return {}

    os.makedirs(output_dir, exist_ok=True)

    exported_tests = {}

    for i, result in enumerate(task_results, 1):
        test_code = result.get("tests", "")
        if not test_code:
            continue

        # 生成測試檔案名稱
        test_filename = f"test_task_{i}.py"
        test_path = os.path.join(output_dir, test_filename)

        if os.path.exists(test_path) and not overwrite:
            print(f"⚠️  Skip: {test_filename} (already exists)")
            continue

        try:
            with open(test_path, "w", encoding="utf-8") as f:
                f.write(test_code)
            exported_tests[test_filename] = test_path
            print(f"✅ Exported test: {test_filename}")
        except Exception as e:
            print(f"❌ Failed to export {test_filename}: {e}")

    return exported_tests


def create_project_structure(
    completed_code: Dict[str, str],
    task_results: list,
    project_name: str = "generated_project",
    include_tests: bool = True,
    overwrite: bool = True,
) -> str:
    """
    創建完整的專案結構，包含代碼、測試和基本配置檔。

    Args:
        completed_code: {filename: code_str}
        task_results: list of TaskResult dicts
        project_name: 專案名稱，用作根目錄
        include_tests: 是否包含測試
        overwrite: 是否覆寫現有檔案（預設 True，確保修改生效）

    Returns:
        專案根目錄的路徑
    """
    # 創建專案根目錄
    os.makedirs(project_name, exist_ok=True)

    # 導出主代碼
    print(f"\n📦 Creating project: {project_name}")
    print("=" * 50)
    exported_code = export_code_to_directory(
        completed_code,
        output_dir=project_name,
        overwrite=overwrite
    )

    # 導出測試
    if include_tests and task_results:
        print("\n🧪 Exporting tests...")
        export_tests_to_directory(
            task_results,
            output_dir=os.path.join(project_name, "tests"),
            overwrite=False
        )

    # 創建 __init__.py（如果需要）
    init_path = os.path.join(project_name, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w", encoding="utf-8") as f:
            f.write("# Generated by Harness\n")
        print(f"✅ Created: __init__.py")

    # 創建 README
    readme_path = os.path.join(project_name, "README.md")
    if not os.path.exists(readme_path):
        readme_content = f"""# {project_name}

Generated by Harness - AI-powered TDD system

## Files

{chr(10).join(f"- `{filename}`" for filename in completed_code.keys())}

## Run Tests

```bash
pytest tests/
```
"""
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)
        print(f"✅ Created: README.md")

    print("=" * 50)
    print(f"✅ Project created: {os.path.abspath(project_name)}")

    return os.path.abspath(project_name)
