"""
harness/github_runner.py — GitHub Actions 觸發入口。

從環境變數讀取 Issue 資訊，呼叫 run_harness()，
push branch，開 PR，在 Issue 留言。

環境變數：
  ISSUE_TITLE     — Issue 標題
  ISSUE_BODY      — Issue 內容
  ISSUE_NUMBER    — Issue 編號（整數）
  REPO            — GitHub repo（格式：owner/repo）
  EXPORT_DIR      — 生成專案的輸出路徑
"""
import os
import subprocess
import sys         # noqa: F401 — used in later tasks


def get_issue_input() -> dict:
    """從環境變數讀取 Issue 資訊。

    Returns:
        {"title": str, "body": str, "number": int, "repo": str, "export_dir": str}

    Raises:
        EnvironmentError: 若缺少必要環境變數
    """
    missing = []
    for key in ["ISSUE_TITLE", "REPO", "EXPORT_DIR"]:
        if not os.environ.get(key):
            missing.append(key)
    number_raw = os.environ.get("ISSUE_NUMBER", "").strip()
    if not number_raw:
        missing.append("ISSUE_NUMBER")
    if missing:
        raise EnvironmentError(f"Missing required environment variables: {', '.join(missing)}")

    return {
        "title": os.environ["ISSUE_TITLE"],
        "body": os.environ.get("ISSUE_BODY", ""),
        "number": int(number_raw),
        "repo": os.environ["REPO"],
        "export_dir": os.environ["EXPORT_DIR"],
    }


def build_user_input(title: str, body: str) -> str:
    """合併 Issue title 和 body 為 run_harness 的 user_input。

    若 body 為空，只回傳 title。
    否則回傳 "title\n\nbody"。
    """
    if not body.strip():
        return title
    return f"{title}\n\n{body}"


def _run_cmd(args: list[str], cwd: str | None = None) -> tuple[bool, str]:
    """執行 CLI 指令，回傳 (success, output)。失敗只 print 警告，不 raise。"""
    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=120,
        )
        return result.returncode == 0, (result.stdout or "").strip()
    except Exception as e:
        return False, str(e)


def push_branch(project_path: str, branch: str) -> bool:
    """Push branch 到 origin。回傳是否成功。"""
    ok, out = _run_cmd(["git", "push", "origin", branch], cwd=project_path)
    if not ok:
        print(f"⚠️  git push failed: {out}")
    return ok


def create_pr(repo: str, branch: str, title: str, issue_number: int) -> str | None:
    """用 gh CLI 開 PR。回傳 PR URL 或 None。"""
    body = f"Closes #{issue_number}\n\nGenerated by Harness from Issue #{issue_number}."
    ok, out = _run_cmd([
        "gh", "pr", "create",
        "--repo", repo,
        "--head", branch,
        "--base", "main",
        "--title", title,
        "--body", body,
    ])
    if not ok:
        print(f"⚠️  gh pr create failed: {out}")
        return None
    return out if out.startswith("https://") else (out.split()[-1] if out else None)


def comment_on_issue(repo: str, issue_number: int, message: str) -> bool:
    """在 Issue 留言。回傳是否成功。"""
    ok, out = _run_cmd([
        "gh", "issue", "comment", str(issue_number),
        "--repo", repo,
        "--body", message,
    ])
    if not ok:
        print(f"⚠️  gh issue comment failed: {out}")
    return ok
