"""
harness/github_runner.py — GitHub Actions 觸發入口。

從環境變數讀取 Issue 資訊，呼叫 run_harness()，
push branch，開 PR，在 Issue 留言。

環境變數：
  ISSUE_TITLE     — Issue 標題
  ISSUE_BODY      — Issue 內容
  ISSUE_NUMBER    — Issue 編號（整數）
  REPO            — GitHub repo（格式：owner/repo）
  EXPORT_DIR      — 生成專案的輸出路徑
"""
import os
import subprocess
import sys

# Placeholder — populated lazily inside main() via deferred import to avoid circular imports.
# Tests can patch harness.github_runner.run_harness directly.
run_harness = None


def get_issue_input() -> dict:
    """從環境變數讀取 Issue 資訊。

    Returns:
        {"title": str, "body": str, "number": int, "repo": str, "export_dir": str}

    Raises:
        EnvironmentError: 若缺少必要環境變數
    """
    missing = []
    for key in ["ISSUE_TITLE", "REPO", "EXPORT_DIR"]:
        if not os.environ.get(key):
            missing.append(key)
    number_raw = os.environ.get("ISSUE_NUMBER", "").strip()
    if not number_raw:
        missing.append("ISSUE_NUMBER")
    if missing:
        raise EnvironmentError(f"Missing required environment variables: {', '.join(missing)}")

    try:
        number = int(number_raw)
    except ValueError:
        raise EnvironmentError(f"ISSUE_NUMBER must be an integer, got: {number_raw!r}")

    return {
        "title": os.environ["ISSUE_TITLE"],
        "body": os.environ.get("ISSUE_BODY", ""),
        "number": number,
        "repo": os.environ["REPO"],
        "export_dir": os.environ["EXPORT_DIR"],
    }


def build_user_input(title: str, body: str) -> str:
    """合併 Issue title 和 body 為 run_harness 的 user_input。

    若 body 為空，只回傳 title。
    否則回傳 "title\n\nbody"。
    """
    if not body.strip():
        return title
    return f"{title}\n\n{body}"


def _run_cmd(args: list[str], cwd: str | None = None) -> tuple[bool, str]:
    """執行 CLI 指令，回傳 (success, output)。失敗只 print 警告，不 raise。"""
    try:
        result = subprocess.run(
            args,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=120,
        )
        # stdout + stderr 都回傳，確保失敗時可見完整錯誤訊息
        output = ((result.stdout or "") + (result.stderr or "")).strip()
        return result.returncode == 0, output
    except Exception as e:
        return False, str(e)


def push_branch(project_path: str, branch: str) -> bool:
    """Push branch 到 origin。回傳是否成功。"""
    ok, out = _run_cmd(["git", "push", "origin", branch], cwd=project_path)
    if not ok:
        print(f"⚠️  git push failed: {out}")
    return ok


def create_pr(repo: str, branch: str, title: str, issue_number: int) -> str | None:
    """用 gh CLI 開 PR。回傳 PR URL 或 None。"""
    body = f"Closes #{issue_number}\n\nGenerated by Harness from Issue #{issue_number}."
    ok, out = _run_cmd([
        "gh", "pr", "create",
        "--repo", repo,
        "--head", branch,
        "--base", "main",
        "--title", title,
        "--body", body,
    ])
    if not ok:
        print(f"⚠️  gh pr create failed: {out}")
        return None
    return out if out.startswith("https://") else (out.split()[-1] if out else None)


def comment_on_issue(repo: str, issue_number: int, message: str) -> bool:
    """在 Issue 留言。回傳是否成功。"""
    ok, out = _run_cmd([
        "gh", "issue", "comment", str(issue_number),
        "--repo", repo,
        "--body", message,
    ])
    if not ok:
        print(f"⚠️  gh issue comment failed: {out}")
    return ok


def upload_artifacts(repo: str, artifacts_dir: str) -> str:
    """把 test_artifacts 目錄壓縮後用 gh 上傳到 GitHub Actions run。
    回傳 artifacts URL 或空字串。
    """
    if not artifacts_dir or not os.path.isdir(artifacts_dir):
        return ""
    # GitHub Actions Artifacts 只能在 workflow 內上傳，
    # 這裡改成把報告路徑印出來讓 workflow 的 upload-artifact step 處理
    print(f"📁 Artifacts 位置：{artifacts_dir}")
    return artifacts_dir


def main() -> None:
    """完整執行流程：
    1. 讀 Issue 環境變數
    2. run_harness()
    3. push branch
    4. 開 PR
    5. 在 Issue 留言
    """
    global run_harness
    if run_harness is None:
        from harness.main import run_harness as _rh  # 延遲 import 避免循環
        run_harness = _rh

    # 讀取 Issue 資訊
    try:
        issue = get_issue_input()
    except EnvironmentError as e:
        print(f"❌ Missing env vars: {e}")
        sys.exit(1)

    repo = issue["repo"]
    issue_number = issue["number"]
    export_dir = issue["export_dir"]
    user_input = build_user_input(issue["title"], issue["body"])

    # slug 只用 issue 編號，不用 body（body 可能含 HTML 圖片等雜訊）
    slug_prefix = f"issue-{issue_number}"
    if slug_prefix not in user_input:
        user_input = f"{slug_prefix} {user_input}"

    # worktree branch 用乾淨的 slug_input，只含 title + issue 號碼
    slug_input = f"issue-{issue_number} {issue['title']}"

    print(f"🚀 Running Harness for Issue #{issue_number}: {issue['title']}")

    # 執行 Harness
    try:
        result = run_harness(user_input=user_input, export_dir=export_dir, git_slug=slug_input)
    except Exception as e:
        print(f"❌ Harness 執行失敗：{e}")
        comment_on_issue(
            repo=repo,
            issue_number=issue_number,
            message=f"## Harness 執行失敗\n\n```\n{e}\n```\n\nIssue #{issue_number} 的需求尚未實作，請檢查 Harness 日誌。",
        )
        sys.exit(1)

    branch = result.get("git_branch")
    project_path = result.get("project_path")

    # Push branch
    if branch and project_path:
        push_branch(project_path=project_path, branch=branch)
    else:
        print("⚠️  No branch/project_path in result, skipping push")

    # 開 PR
    pr_url = None
    if branch:
        pr_url = create_pr(
            repo=repo,
            branch=branch,
            title=issue["title"],
            issue_number=issue_number,
        )

    # Issue 留言
    passed = result.get("passed", 0)
    total = result.get("total", 0)
    forced = result.get("forced", 0)
    task_results = result.get("task_results", [])

    # 產生每個 task 的測試摘要
    task_lines = []
    for r in task_results:
        if r.get("forced"):
            icon = "⚠️"
            status = "FORCED"
        elif r.get("passed"):
            icon = "✅"
            status = "PASS"
        else:
            icon = "❌"
            status = "FAIL"
        task_lines.append(f"| {r.get('task_id')} | {icon} {status} | {r.get('feedback', '')[:80]} |")

    task_table = ""
    if task_lines:
        task_table = (
            "\n\n### 測試結果明細\n\n"
            "| Task | 狀態 | 說明 |\n"
            "|------|------|------|\n"
            + "\n".join(task_lines)
        )

    # 檢查是否有 Playwright artifacts
    artifacts_dir = os.path.join(os.path.dirname(export_dir) if export_dir else ".", "test_artifacts")
    artifacts_note = ""
    if os.path.isdir(artifacts_dir):
        screenshots = [f for f in os.listdir(os.path.join(artifacts_dir, "screenshots")) if f.endswith(".png")] if os.path.isdir(os.path.join(artifacts_dir, "screenshots")) else []
        report_exists = os.path.exists(os.path.join(artifacts_dir, "report.html"))
        if screenshots or report_exists:
            artifacts_note = f"\n\n### 測試 Artifacts\n📸 截圖：{len(screenshots)} 張　📄 HTML 報告：{'有' if report_exists else '無'}\n（詳見 GitHub Actions Run → Artifacts）"

    if pr_url:
        comment_msg = (
            f"## ✅ Harness 完成\n\n"
            f"PR：{pr_url}\n\n"
            f"**結果：** {passed}/{total} tasks passed"
            + (f"，{forced} forced（品質未驗證）" if forced else "")
            + task_table
            + artifacts_note
            + f"\n\nCloses #{issue_number}"
        )
    else:
        comment_msg = (
            f"## ⚠️  Harness 完成但 PR 建立失敗\n\n"
            f"Branch：`{branch}`\n\n"
            f"**結果：** {passed}/{total} tasks passed"
            + (f"，{forced} forced" if forced else "")
            + task_table
            + artifacts_note
            + "\n\n請手動建立 PR。"
        )

    comment_on_issue(repo=repo, issue_number=issue_number, message=comment_msg)
    print(f"✅ Done. PR: {pr_url or '(failed to create)'}")


if __name__ == "__main__":
    main()
